### ISSUE TITLE
Using canbench with Application subnet

### ISSUE THREAD

**Issue by wasm-forge** [dfinity/canbench#61] opened 2024-08-26 06:09 UTC
Hello,

I am trying to estimate a function with canbench, the test is storing 100Mb of data into stable memory.
The canbench reports only about 50k instructions, which seems too low for this amount of work.

I have made a normal pocketIc test, it reports about 124 million instructions (an expected number for this task). If I switch pocketIc creation from
```
let pic = PocketIc::new();
```
to 
```
let pic = PocketIcBuilder::new().with_benchmarking_system_subnet().build();
```

My estimation drops to 50k as well. Is there a way to make canbench also use the application subnet?

If you need, you can see the project [here](https://github.com/wasm-forge/treemap_chunks), see the test and bench functions: `write_memory_test` and `write_memory_bench` in [lib.rs](https://github.com/wasm-forge/treemap_chunks/blob/main/src/treemap_chunks_backend/src/lib.rs).

Regards,
Stan

**Comment by ielashi** [comment] 2024-08-26 09:26
@wasm-forge Thanks a lot for reporting this. I agree, we should be using the application subnet config in canbench rather than system subnets. I just created a PR to address this.

**Comment by ielashi** [comment] 2024-08-26 14:17
@wasm-forge The fix has now been merged and I'll be preparing a new canbench release.

**Comment by ielashi** [comment] 2024-08-27 09:36
canbench 0.1.5 has been released. @wasm-forge I believe the issue is addressed now.

**Closed by ielashi** 2024-08-27 09:36 UTC
